# Generated by Django 2.1.5 on 2019-01-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_title', models.CharField(max_length=20)),
                ('a_content', models.CharField(max_length=1500)),
                ('a_pre', models.CharField(max_length=20)),
                ('a_time', models.DateField(auto_now_add=True)),
                ('a_category', models.IntegerField()),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Bei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=20)),
                ('b_pre', models.CharField(max_length=20)),
                ('b_b', models.IntegerField()),
            ],
            options={
                'db_table': 'bei',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=20)),
                ('c_pre', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
